### ISSUE TITLE
Sidemenu is blocking some content

### ISSUE THREAD

**Issue by manugb** [holden-caulfield/redux-workshop#2]
Hi
I going tonight to the talk and I was following the readme
When I try localhost:3000, I notice that the right sidemenu showing Reset, Revert, Sweep, Commit
is blocking the Done Tasks area.
Maybe the content area(everything with the blue background) should be centered?

**Comment by holden-caulfield** [comment]
CTRL+H would hide the debug tool bar... I will add a note on the readme file
